### ISSUE TITLE
Backport from atom/language-hyperlink

### ISSUE THREAD

**Issue by Fank** [textmate/hyperlink-helper.tmbundle#5]
@infininight I wana backport the changes from the ported atom repository. Sames as you does in the perl repository.
Can you give some instructions how you do that? So i can do that on my own?

**Comment by infininight** [comment]
Because the format of Atom and TextMate bundles are so different it is very much a completely manual process. The steps I take for the Perl bundle is to first cherry-pick the commit to get the metadata, then delete all content of the commit and port the content by hand keeping in mine the escaping and formatting differences. Laborious but the best manner I have currently.
